# Generated by Django 2.0.10 on 2019-02-06 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20190206_1848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('sem categoria', 'sem categoria'), ('web design', 'web wesign'), ('photoshop', 'photoshop'), ('html5 e css3', 'html5 e css3'), ('web application', 'web application'), ('seo', 'seo')], default='sem categoria', max_length=20),
        ),
    ]
